"""update unique constraint

Revision ID: a713a1df1b20
Revises: ed332088ab9f
Create Date: 2023-02-28 23:01:31.838707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a713a1df1b20'
down_revision = 'ed332088ab9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('similar_exercises')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_exercises', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
